export function generateHeader(): string {
  return `<h1 align="center">Hi <img src="public/webp/peepoHey.webp" alt="Hi" width="30" height="30" />, I'm Petar Zarkov</h1>
<h3 align="center">A passionate software developer from Bulgaria</h3>
<p align="center">This page is auto generated by the repo itself</p>

<p align="center">
  <img src="https://komarev.com/ghpvc/?username=petarzarkov&label=Profile%20views&color=0e75b6&style=flat" alt="petarzarkov" />
</p>

<a href="https://petarzarkov.github.io/petarzarkov/" target="_blank">
Check out the auto generated github pages as well
</a>`;
}
